### ISSUE TITLE
README

### ISSUE THREAD

**Issue by zeyad-mansour** [ShashankRaghuraj/AI-Tutorial#1]
I was looking through the README, and I was confused on your explanation for some of the things that you described.

For example, you say that a virtual environment is "basically a place that doesn’t physically happen on your computer it takes place, well, virtually. This is important because some of the libraries that are needed to download, are very hard to get to work without a virtual environment."

I'm not sure exactly what you mean here since virtual environments are executed on the local machine, and I don't think that they aid in the installation of libraries; instead, they are used to avoid the global installation of packages or to separate different project dependencies (e.g. python versions).

**Comment by ShashankRaghuraj** [comment]
Correct, you are right. I will change that in the read me file. I explained it like that in the lecture but forgot to write it here
